### PR TITLE
Added search to nav bar

### PR DESCRIPTION
**Pull request by spstapleton**
If screen width is less than 500px search is hidden.

### CODE REVIEW

**Comment by Wingar** [comment]
:+1:

**Comment by tasermonkey** [comment]
is what it looks like in landscape mode on my phone.  

In portrait mode its not visible and I notice no difference than before

**Comment by tasermonkey** [comment]
:+1: as well btw.  I will let @walkeriniraq merge it if he wishes.

**Comment by tasermonkey** [comment]
Whoops, forgot I merged his branch locally to test.  :-)

**Comment by Wingar** [comment]
Hmm, discovered an issue. If you just press the search button, it 500's on the server (no route), and breaks the UI. It doesn't just redirect to the main search page, it tries an empty search.

**Pull request merged**
